import Footer from "@/components/Footer";
import Header from "@/components/Header";
// import DashboardTable from "@/components/Table/DashboardTable";
import TopBar from "@/components/TopBar";
import React from "react";
import Sidebar from "@/components/Sidebar";
import CardMain from "@/components/Cards/CardMain";
import Head from "next/head";

function dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopBar />
      <main className="mb-20">
        <div className="container-box flex">
          <Sidebar />
          <CardMain />
        </div>
      </main>
      <Footer />
    </>
  );
}

export default dashboard;
