"use client";
import Footer from "@/components/Footer";
import React, { useEffect, useRef, useState } from "react";
import arrow from "@/assets/imgs/icons/arrowDown.svg";
import Header from "@/components/Header";
import TopBar from "@/components/TopBar";
import Sidebar from "@/components/Sidebar";
import { Button } from "@/ui";
import Image from "next/image";
import Card from "@/components/Cards/Card";
import Head from "next/head";

function page() {
  const [open, setOpen] = useState(false);
  const [text, setText] = useState("Показать всё");

  const menuRef = useRef(null);
  const textRef = useRef(null);
  const arrowRef = useRef(null);
  const cardmainRef = useRef(null);
  const cardmainRefText = useRef(null);

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (
        e.target !== menuRef.current &&
        e.target !== cardmainRef.current &&
        e.target !== cardmainRefText.current &&
        e.target !== arrowRef.current &&
        e.target !== textRef.current
      ) {
        setOpen(false);
      }
    };

    window.addEventListener("click", handleClickOutside);

    return () => {
      window.removeEventListener("click", handleClickOutside);
    };
  }, [open]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopBar />
      <main className="mb-20">
        <div className="container-box flex">
          <Sidebar />
          <section className="cardmain w-full">
            <div className="cardmain__filters flex items-center">
              <p>Сортировать по:</p>
              <div className="cardmain__main-select">
                <div
                  ref={cardmainRef}
                  onClick={() => setOpen(!open)}
                  className="cardmain__filter flex items-center justify-between flex-row-reverse"
                >
                  <Image src={arrow} alt="" />
                  <span ref={cardmainRefText}>{text}</span>
                </div>
                <div
                  ref={menuRef}
                  className={open === true ? `cardmain__select` : "hidden"}
                >
                  <p
                    style={
                      text === "Сначала новые"
                        ? { color: "#2272d4" }
                        : { color: "#333" }
                    }
                    onClick={() => setText("Сначала новые")}
                  >
                    Сначала новые
                  </p>
                  <p
                    style={
                      text === "Сначала старые"
                        ? { color: "#2272d4" }
                        : { color: "#333" }
                    }
                    onClick={() => setText("Сначала старые")}
                  >
                    Сначала старые
                  </p>
                  <p
                    style={
                      text === "Сначала дороже"
                        ? { color: "#2272d4" }
                        : { color: "#333" }
                    }
                    onClick={() => setText("Сначала дороже")}
                  >
                    Сначала дороже
                  </p>
                  <p
                    style={
                      text === "Сначала дешевле"
                        ? { color: "#2272d4" }
                        : { color: "#333" }
                    }
                    onClick={() => setText("Сначала дешевле")}
                  >
                    Сначала дешевле
                  </p>
                </div>
              </div>
            </div>
            <div className="cardmain__lists">
              <Card />
              <Card />
              <Card />
              <Card />
              <Card />
              <Card />
            </div>
            <Button className="w-full cardmain__btn" text="Показать еще" />
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}

export default page;
